# Generated by Django 3.2 on 2021-04-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
    ]
