# Generated by Django 3.2 on 2021-04-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notes',
            field=models.ManyToManyField(to='notes.Note'),
        ),
    ]
