# Generated by Django 3.2 on 2021-04-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notes',
        ),
    ]
