# Generated by Django 3.2 on 2021-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notes',
            field=models.ManyToManyField(related_name='_notes_note_notes_+', to='notes.Note'),
        ),
    ]
