# Generated by Django 3.2 on 2021-04-24 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20210424_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='title'),
            preserve_default=False,
        ),
    ]
