# Generated by Django 3.2 on 2021-04-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalitem',
            name='parent_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='parent_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_item', to='contenttypes.contenttype'),
        ),
    ]
