# Generated by Django 3.2 on 2021-04-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_alter_journalitem_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalitem',
            old_name='parent_id',
            new_name='child_id',
        ),
        migrations.RenameField(
            model_name='journalitem',
            old_name='parent_type',
            new_name='child_type',
        ),
    ]
