# Generated by Django 3.2.5 on 2021-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_alter_journalitem_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalitem',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
    ]
