# Generated by Django 3.2 on 2021-04-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0009_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.note')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
            ],
            bases=('notes.note',),
        ),
    ]
