# Generated by Django 3.2 on 2021-04-24 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('N', 'Note'), ('T', 'Task'), ('E', 'Event')], max_length=1)),
                ('is_important', models.BooleanField(default=False, verbose_name='important')),
                ('is_research', models.BooleanField(default=False, verbose_name='research')),
                ('is_good_idea', models.BooleanField(default=False, verbose_name='good idea')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name='date edited')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
