# Generated by Django 3.2 on 2021-04-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20210425_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalitem',
            options={'ordering': ['date_created']},
        ),
    ]
