# Generated by Django 3.2 on 2021-04-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_good_idea',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_research',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='note',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
